name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.233.126.119 << 'EOF'
          cd /home/ubuntu/your-app-folder

          echo "Pulling latest code..."
          git pull origin main

          echo "Installing dependencies..."
          npm install

          echo "Building Next.js app..."
          npm run build

          echo "Restarting app..."
          pm2 restart all || pm2 start npm --name "next-app" -- start

          echo "Deployment done!"
        EOF
