name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip << 'EOF'
          cd ~/apps/nextjs-app
          pm2 stop all || true
          git pull origin main || true
          npm install
          npm run build
          pm2 start npm --name "nextjs-app" -- start
          pm2 save
        EOF
